
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-gauchoride-s24-5pm-8
owner: ucsb-cs156-s24
repo_name: proj-gauchoride-s24-5pm-8
pull_requests: [{"author":{"id":"U_kgDOB3DoXA","is_bot":false,"login":"TheRealAndrxw","name":"Andrew Vosgueritchian"},"headRefName":"AV-DriverAvailabilityIndexPage-Bug","number":20,"title":"AV-Updated DriverAvailability Index Backend URL for Drivers","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-8/pull/20"}]
