
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-gauchoride-s24-5pm-8
owner: ucsb-cs156-s24
repo_name: proj-gauchoride-s24-5pm-8
pull_requests: [{"author":{"id":"U_kgDOB3DoXA","is_bot":false,"login":"TheRealAndrxw","name":"Andrew Vosgueritchian"},"headRefName":"AV-SwaggerNavbar-Feature","number":34,"title":"AV-Created Feature for Swagger Navbar to Env Var Toggle","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-8/pull/34"},{"author":{"id":"MDQ6VXNlcjQzMDE2ODM5","is_bot":false,"login":"KarstenLansing","name":"Karsten James Lansing"},"headRefName":"kl-DriverIdDropdownShiftForm","number":33,"title":"Kl - FEATURE: Change Driver Id text fields to dropdown","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-8/pull/33"},{"author":{"id":"MDQ6VXNlcjQyMTYwOTky","is_bot":false,"login":"xinyao-song","name":"XinYao Song"},"headRefName":"xs-DriverAvailabilitiesCreate","number":24,"title":"XS - EPIC: Improve usability of the DriverAvailabilities Create Page","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-8/pull/24"},{"author":{"id":"MDQ6VXNlcjQyMTYwOTky","is_bot":false,"login":"xinyao-song","name":"XinYao Song"},"headRefName":"xs-DriverAvailabiltyUsability","number":23,"title":"XS - FEATURE: Improve the usability of the admin DriverAvailabiltyIndexPage","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-8/pull/23"}]
