
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s24/proj-gauchoride-s24-5pm-8
owner: ucsb-cs156-s24
repo_name: proj-gauchoride-s24-5pm-8
pull_requests: [{"author":{"id":"U_kgDOB3DoXA","is_bot":false,"login":"TheRealAndrxw","name":"Andrew Vosgueritchian"},"headRefName":"AV-ToggleRider","number":28,"title":"AV-Created ToggleRider Feature for Rider Applications","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-8/pull/28"},{"author":{"id":"U_kgDOB00C0g","is_bot":false,"login":"spark686","name":""},"headRefName":"sp-feature-add","number":26,"title":"sp-Rider can see whether their ride request is assigned or not","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-8/pull/26"},{"author":{"id":"MDQ6VXNlcjQzMDE2ODM5","is_bot":false,"login":"KarstenLansing","name":"Karsten James Lansing"},"headRefName":"kl-selectDriverFromDropdown","number":25,"title":"KL - FEATURE: Admin should be able to select driver from dropdown for assigning ride request","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-8/pull/25"},{"author":{"id":"MDQ6VXNlcjQyMTYwOTky","is_bot":false,"login":"xinyao-song","name":"XinYao Song"},"headRefName":"xs-DriverAvailabilitiesCreate","number":24,"title":"XS - EPIC: Improve usability of the DriverAvailabilities Create Page","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-8/pull/24"},{"author":{"id":"MDQ6VXNlcjQyMTYwOTky","is_bot":false,"login":"xinyao-song","name":"XinYao Song"},"headRefName":"xs-DriverAvailabiltyUsability","number":23,"title":"XS - FEATURE: Improve the usability of the admin DriverAvailabiltyIndexPage","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-8/pull/23"},{"author":{"id":"MDQ6VXNlcjQyMTYwOTky","is_bot":false,"login":"xinyao-song","name":"XinYao Song"},"headRefName":"xs-toBeRiderNav","number":22,"title":"XS - BUG: User not logged in can see \"Apply to be a Rider\" on navbar","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-8/pull/22"},{"author":{"id":"U_kgDOB3DoXA","is_bot":false,"login":"TheRealAndrxw","name":"Andrew Vosgueritchian"},"headRefName":"AV-DriverAvailabilityIndexPage-Bug","number":20,"title":"AV-Updated DriverAvailability Index Backend URL for Drivers","url":"https://github.com/ucsb-cs156-s24/proj-gauchoride-s24-5pm-8/pull/20"}]
